### ISSUE TITLE
Vprašanje glede modifikacij

### ISSUE THREAD

**Issue by TineBine** [TineBine/Projetk-FP#2]
Pozdravljeni!

Potrebujeva nasvet glede nekaterih modifikacij iz članka. Pri 3. Modifikaciji je v članku predpostavljeno, da je varianca znana in lahko iz nje izpeljemo parameter q(V), ki je uporabljen v formuli za pričakovano trajanje. Pri tem ni naveden noben primer take izpeljave, zato imava težave, kako smiselno določiti ta parameter. Prav tako naju pri 5. Modifikaciji zanima, kako bi bilo za posamezna opravila najbolje določiti podintervale in kakšne verjetnosti naj na njih zavzamejo funkcije gostot porazdelitev.

Hvala za odgovor in lep pozdrav,
Tine Markočič

**Comment by jaanos** [comment]
Varianca je podana z enačbo (6) v članku - če je znana in so znani še *a*, *b*, *M*, potem se lahko vrednost *q* izrazi iz nje. Verjetno bo najbolje, da se po vstavitvi parametrov reši numerično (v splošnem gre za polinom tretje stopnje v *q*) in vzame največjo od ničel (tj., taka, da velja *q* > 1).

V primeru, ko je znana verjetnost podintervala, gre samo za to, da za opravilo, katerega trajanje zavzame vrednost na intervalu [*a*, *b*], vesta, da je verjetnost, da bo trajanje na podintervalu [*a*<sub>1</sub>, *b*<sub>1</sub>] (za neka *a* < *a*<sub>1</sub> < *b*<sub>1</sub> < *b*), enaka ε. Tukaj torej namesto najverjetnejše vrednosti *M* določita ta podinterval in njegovo verjetnost. Najbrž bi bilo smiselno, da gre na nek način za najbolj verjeten podinterval - torej nekako okoli siceršnje vrednosti *M*, in pa z verjetnostjo ε > (*b*<sub>1</sub> - *a*<sub>1</sub>) / (*b* - *a*) (če imata določeno porazdelitev za ta dogodek, lahko ε izračunata kot razliko kumulativnih verjetnosti v *b*<sub>1</sub> in *a*<sub>1</sub>). Načeloma pa bi to moralo delovati, če je tak interval manj verjeten, tako da lahko poskusita tudi s takimi primeri.

Kot rečeno, je članek samo neko vodilo, in ni nujno, da se lotita čisto vsakega primera, ki je v njem podan.
